# .github/configs/label-commenter-config.yml

labels:

  - name: '长期失联'
      labeled:
        issue:
          action: close
          body: |
            **⚠️ 抱歉，您的网站长期打不开，现已暂时下架。**
  
            如果您确认可以打开，请在下方评论告知，我们会在人工审核通过后恢复上架。
  
  - name: '无效主题'
      labeled:
        issue:
          action: close
          body: |
            **⚠️ 抱歉，由于您已经不再使用Stellar，现已暂时下架。**
  
            期待您的回归，如果信息有误，请在下方评论告知，我们会在人工审核通过后恢复上架。
