# Issue 解析器配置
issue_parser:
  enabled: true
  repo: xaoxuu/hexo-theme-stellar-showcase # 仓库持有者/仓库名
  sort: updated-desc # 排序，按最近更新，取消此项则按创建时间排序
  exclude: ["审核中", "非Stellar站点", "无法访问"]  # 黑名单标签，包含这些标签的 issue 将被过滤


# 网站检查器配置
site_checker:
  enabled: true
  timeout: 10000  # 请求超时时间（毫秒）
  retry_times: 3  # 重试次数
